INITIAL_SONGS_PATH = "/api/songs/initial"
COMMON_PATH = "/api/common/status"
SONGS_BASE_PATH = "/api/songs"
SONGS_RATING_PATH = "/api/songs/{song_id}/rating"
SONGS_SCORE_PATH = "/api/songs/{song_id}/score"
