LIST_SONG_EXPECTED_FULL_DATA_WITHOUT_IDS = {
    "average_difficulty": 10.323636363636364,
    "links": {
        "last": {"href": "http://localhost/api/songs?page=1&page_size=15"},
        "next": None,
        "prev": None,
        "self": {"href": "http://localhost/api/songs?page=1&page_size=15"},
    },
    "songs": [
        {
            "artist": "The You",
            "difficulty": 14.6,
            "level": 13,
            "rating": None,
            "released": "Wed, 26 Oct 2016 00:00:00 GMT",
            "title": "Lycanthropic Metamorphosis",
        },
        {
            "artist": "The You",
            "difficulty": 9.1,
            "level": 9,
            "rating": None,
            "released": "Wed, 03 Feb 2010 00:00:00 GMT",
            "title": "A New Kennel",
        },
        {
            "artist": "Mr Fastfinger",
            "difficulty": 15.0,
            "level": 13,
            "rating": None,
            "released": "Fri, 11 May 2012 00:00:00 GMT",
            "title": "Awaki-Waki",
        },
        {
            "artist": "The You",
            "difficulty": 13.22,
            "level": 13,
            "rating": None,
            "released": "Sat, 20 Dec 2014 00:00:00 GMT",
            "title": "You've Got The Power",
        },
        {
            "artist": "The You",
            "difficulty": 10.98,
            "level": 9,
            "rating": None,
            "released": "Fri, 01 Jan 2016 00:00:00 GMT",
            "title": "Wishing In The Night",
        },
        {
            "artist": "The You",
            "difficulty": 14.66,
            "level": 13,
            "rating": None,
            "released": "Sat, 27 Apr 2013 00:00:00 GMT",
            "title": "Opa Opa Ta Bouzoukia",
        },
        {
            "artist": "The You",
            "difficulty": 2.0,
            "level": 3,
            "rating": None,
            "released": "Tue, 01 Mar 2016 00:00:00 GMT",
            "title": "Greasy Fingers - boss level",
        },
        {
            "artist": "The You",
            "difficulty": 5.0,
            "level": 6,
            "rating": None,
            "released": "Fri, 01 Apr 2016 00:00:00 GMT",
            "title": "Alabama Sunrise",
        },
        {
            "artist": "The You",
            "difficulty": 9.0,
            "level": 9,
            "rating": None,
            "released": "Sun, 01 May 2016 00:00:00 GMT",
            "title": "Can't Buy Me Skills",
        },
        {
            "artist": "The You",
            "difficulty": 13.0,
            "level": 13,
            "rating": None,
            "released": "Wed, 01 Jun 2016 00:00:00 GMT",
            "title": "Vivaldi Allegro Mashup",
        },
        {
            "artist": "The You",
            "difficulty": 7.0,
            "level": 6,
            "rating": None,
            "released": "Fri, 01 Jul 2016 00:00:00 GMT",
            "title": "Babysitting",
        },
    ],
}

LIST_SONG_EXPECTED_PAGING_DATA = {
    "last": {"href": "http://localhost/api/songs?page=3&page_size=4"},
    "next": {"href": "http://localhost/api/songs?page=3&page_size=4"},
    "prev": {"href": "http://localhost/api/songs?page=1&page_size=4"},
    "self": {"href": "http://localhost/api/songs?page=2&page_size=4"},
}
